#include <numsim_codegen/targets/calculix_umat.h>

#include "calculix_boundary.h"

#include <numsim_codegen/recipe.h>

#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace numsim::codegen {

namespace {

// CalculiX's native `umat_user` argument list (see umat_main.f's CALL). All
// Fortran arguments are passed by reference; default `integer` maps to `int`,
// `real*8` to `double`. The leading `character*80` name adds a hidden trailing
// length argument under gfortran's calling convention — `int` (4-byte), matching
// ccx's own Fortran→C boundary (call_external_umat_user.c declares the same
// hidden length as `const int`); default `INTEGER` is 4-byte (the ccx Makefile
// uses no -fdefault-integer-8). We only *use* a handful (elconloc, emec, icmd,
// stre, stiff); the rest are named in comments so the ABI (argument count +
// order + widths) matches exactly. This prototype is also what the ABI-driver
// test declares, and must match the `umat_main.f` CALL in the linked `ccx`.
constexpr char const *kUmatUserSignature = R"(extern "C" void umat_user_(
    char *      /*amat*/,      int *    /*iel*/,     int *    /*iint*/,
    int *       /*kode*/,      double * elconloc,    double * emec,
    double *    /*emec0*/,     double * /*beta*/,    double * /*xokl*/,
    double *    /*voj*/,       double * /*xkl*/,     double * /*vj*/,
    int *       /*ithermal*/,  double * /*t1l*/,     double * /*dtime*/,
    double *    /*time*/,      double * /*ttime*/,   int *    icmd,
    int *       /*ielas*/,     int *    /*mint_*/,   int *    /*nstate_*/,
    double *    /*xstateini*/, double * /*xstate*/,  double * stre,
    double *    stiff,         int *    /*iorien*/,  double * /*pgauss*/,
    double *    /*orab*/,      double * /*pnewdt*/,  int *    /*ipkon*/,
    int         /*amat_len*/))";

} // namespace

auto CalculiXUMATTarget::emit(ConstitutiveModel const &model) const
    -> std::vector<EmittedFile> {
  // Emit the Layer-2 body FIRST (also lets History/unsupported roles throw their
  // own diagnostics), then validate the scope + collect the boundary variables
  // (shared with the external target). The canonical order is read post-emit —
  // the same order the generated signature uses — so the wrapper's call cannot
  // drift from `_compute` (issue #77). Gating the linalg include on the
  // emitter's usage marker (not a re-derived predicate) cannot drift either.
  std::string const body = model.emit_compute_function(m_la);
  bool const needs_la = body.find(m_la.usage_marker()) != std::string::npos;

  auto const scope = detail::scan_calculix_scope(model, "CalculiXUMATTarget");

  std::ostringstream os;
  os << "// Auto-generated by numsim-codegen. Do not edit.\n";
  os << "//\n";
  os << "// CalculiX user material (umat_user ABI). Link this object into `ccx`\n";
  os << "// built from source in place of the stock umat_user.f; drive it with a\n";
  os << "// deck material whose NAME begins with `USER` (e.g. `USERELAS`) +\n";
  os << "// `*USER MATERIAL, CONSTANTS=" << scope.params.size() << "` — the "
        "constants\n";
  os << "// must be listed in this recipe's parameter order (see below).\n\n";
  os << "#include <tmech/tmech.h>\n";
  os << "#include <cmath>\n";
  if (needs_la) {
    for (auto const &inc : m_la.includes()) os << "#include " << inc << "\n";
  }
  os << "\n";
  os << body;
  os << "\n";

  // ── The umat_user boundary wrapper ───────────────────────────────────────
  os << kUmatUserSignature << " {\n";

  os << "  // Material constants, in *USER MATERIAL declaration order. The deck's\n";
  os << "  // CONSTANTS count MUST equal this parameter count (" << scope.params.size()
     << ") — CalculiX passes no count to umat_user, so a mismatch is a silent\n";
  os << "  // out-of-bounds read.\n";
  for (std::size_t k = 0; k < scope.params.size(); ++k) {
    os << "  double const " << scope.params[k] << " = elconloc[" << k << "];\n";
  }

  os << "  // Strain in: CalculiX passes the tensorial Lagrange strain in\n";
  os << "  // abq_std order {11,22,33,12,13,23}; abq_std<3,false> reads it as a\n";
  os << "  // full symmetric tensor with no engineering-shear scaling (verified\n";
  os << "  // by a simple-shear ccx run: eps12=0.005 -> sig12=0.007).\n";
  os << "  tmech::adaptor<double const, 3, 2, tmech::abq_std<3, false>> "
     << scope.strain.name << "_ad(emec);\n";
  os << "  // Stress out: written straight into stre(6) in the same order.\n";
  os << "  tmech::adaptor<double, 3, 2, tmech::abq_std<3, false>> "
     << scope.stress.name << "_ad(stre);\n";
  os << "  // Consistent tangent: fill a 6x6 (row-major) via abq_std<3,false>.\n";
  os << "  // For the minor-symmetric C emitted from a symmetric-strain recipe\n";
  os << "  // this 6x6 IS CalculiX's engineering stiffness D-matrix (no factors).\n";
  os << "  double " << scope.tangent.name << "_D6[36];\n";
  os << "  tmech::adaptor<double, 3, 4, tmech::abq_std<3, false>> "
     << scope.tangent.name << "_ad(" << scope.tangent.name << "_D6);\n";

  // Build the call in canonical argument order (issue #77): map each role to the
  // local wrapper actual.
  os << "\n  " << model.name() << "_compute(\n";
  bool first = true;
  for (auto const &a : canonical_arguments(RecipeView{model})) {
    if (!first) os << ",\n";
    first = false;
    switch (a.role) {
    case ArgSpec::Role::ScalarParam:
      os << "      " << a.name; // local const from elconloc
      break;
    case ArgSpec::Role::TensorInput:
    case ArgSpec::Role::TensorOutput:
    case ArgSpec::Role::TensorTangentOutput:
      os << "      " << a.name << "_ad"; // boundary adaptor
      break;
    // Unreachable: scan_calculix_scope rejected every other role. Enumerated (no
    // default:) so a new ArgSpec::Role is a -Wswitch warning here too.
    case ArgSpec::Role::ScalarInput:
    case ArgSpec::Role::StateOld:
    case ArgSpec::Role::StateCurrentRead:
    case ArgSpec::Role::TimeStep:
    case ArgSpec::Role::ScalarOutput:
    case ArgSpec::Role::NewtonStateOut:
      throw std::runtime_error(
          "CalculiXUMATTarget: internal error — unrejected role reached the "
          "call site for '" + a.name + "'");
    }
  }
  os << ");\n\n";

  detail::emit_stiff21_packing(os, scope.tangent.name + "_D6", "stiff", "*icmd",
                               "  ");
  os << "}\n";

  return {EmittedFile{model.name() + "_umat.cpp", os.str(), "",
                      EmittedFile::Kind::Source}};
}

auto CalculiXUMATTarget::target_name() const -> std::string {
  return "CalculiXUMAT";
}

} // namespace numsim::codegen
