#include <numsim_codegen/targets/calculix_external.h>

#include "calculix_boundary.h"

#include <numsim_codegen/recipe.h>

#include <cctype>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace numsim::codegen {

namespace {

// The `calculixptr` typedef from call_external_umat_user.c. Quantities are
// NATIVE: STRAN1=emec (tensorial, {11,22,33,12,13,23}), STRESS=stre,
// DDSDDE=stiff(21), MPROPS=the *USER MATERIAL constants (NPROPS is ccx's `kode`,
// not a count). Trailing `int size` is the amat length, BY VALUE. Only the
// arguments we use are named.
constexpr char const *kExternalSignature = R"(extern "C" void NCG_UMAT(
    char const *   /*amat*/,   int const *    /*iel*/,    int const *    /*iint*/,
    int const *    /*NPROPS*/, double const * MPROPS,     double const * STRAN1,
    double const * /*STRAN0*/, double const * /*beta*/,   double const * /*F0*/,
    double const * /*voj*/,    double const * /*F1*/,     double const * /*vj*/,
    int const *    /*ithermal*/, double const * /*TEMP1*/, double const * /*DTIME*/,
    double const * /*time*/,   double const * /*ttime*/,  int const *    icmd,
    int const *    /*ielas*/,  int const *    /*mi*/,     int const *    /*NSTATV*/,
    [[maybe_unused]] double const * STATEV0,
    [[maybe_unused]] double *       STATEV1,
    double *       STRESS,
    double *       DDSDDE,      int const *    /*iorien*/, double const * /*pgauss*/,
    double const * /*orab*/,   double *       /*PNEWDT*/, int const *    /*ipkon*/,
    int            /*size*/))";

// The library name ccx parses out of `@<LIB>_NCG_UMAT`: uppercase, alphanumeric
// only. Underscores are dropped so the first `_` splits LIB from FUNC.
// LOSSY — Mat_1, MAT1 and mat1 all map to MAT1, and the .so filename is the only
// namespace (every plugin exports NCG_UMAT), so callers must avoid collisions.
auto library_name(std::string const &model) -> std::string {
  std::string out;
  for (char c : model)
    if (std::isalnum(static_cast<unsigned char>(c)))
      out.push_back(
          static_cast<char>(std::toupper(static_cast<unsigned char>(c))));
  return out;
}

} // namespace

auto CalculiXExternalTarget::emit(ConstitutiveModel const &model) const
    -> std::vector<EmittedFile> {
  std::string const body = model.emit_compute_function(m_la);
  bool const needs_la = body.find(m_la.usage_marker()) != std::string::npos;

  auto const scope =
      detail::scan_calculix_scope(model, "CalculiXExternalTarget");

  auto const lib = library_name(model.name());
  if (lib.empty()) {
    throw std::runtime_error(
        "CalculiXExternalTarget: recipe '" + model.name() +
        "' has no alphanumeric characters in its name, so it maps to an empty "
        "library name (ccx would reject the deck). Rename the model.");
  }

  std::ostringstream os;
  os << "// Auto-generated by numsim-codegen. Do not edit.\n";
  os << "//\n";
  os << "// CalculiX external behaviour, dlopen'd at runtime. Build as:\n";
  os << "//   g++ -std=c++23 -O2 -fPIC -shared this.cpp -I<tmech/include> -o lib"
     << lib << ".so\n";
  os << "// Deck:  *MATERIAL, NAME=@" << lib << "_NCG_UMAT\n";
  os << "//        *USER MATERIAL, CONSTANTS=" << scope.params.size() << "\n";
  os << "// CONSTANTS must equal the parameter count (" << scope.params.size()
     << "): MPROPS is read positionally, unchecked.\n";
  os << "//\n";
  os << "// Each call reads constants + strain, evaluates, packs stress +\n";
  os << "// tangent. Constants are read FRESH per call: ccx interpolates them by\n";
  os << "// temperature, so they can vary.\n\n";
  os << "#include <tmech/tmech.h>\n";
  os << "#include <cmath>\n";
  if (needs_la) {
    for (auto const &inc : m_la.includes()) os << "#include " << inc << "\n";
  }
  os << "\n";
  os << body;
  os << "\n";

  // A per-thread stateless evaluator: no cached constants.
  os << "namespace {\n\n";
  os << "// Stateless, cached per thread (ccx threads the element loop). Holds no\n";
  os << "// constants: they are read from MPROPS each call, since ccx may vary them\n";
  os << "// and one library may serve several *MATERIAL blocks.\n";
  os << "struct ncg_material {\n";
  os << "  void evaluate([[maybe_unused]] double const *mprops,\n";
  os << "                double const *strain_in,\n";
  os << "                double *stress_out, double *tangent_stiff, int icmd) const {\n";
  for (std::size_t k = 0; k < scope.params.size(); ++k) {
    os << "    double const " << scope.params[k] << " = mprops[" << k << "];\n";
  }
  os << "    tmech::adaptor<double const, 3, 2, tmech::abq_std<3, false>> "
     << scope.strain.name << "_ad(strain_in);\n";
  os << "    tmech::adaptor<double, 3, 2, tmech::abq_std<3, false>> "
     << scope.stress.name << "_ad(stress_out);\n";
  os << "    double " << scope.tangent.name << "_D6[36];\n";
  os << "    tmech::adaptor<double, 3, 4, tmech::abq_std<3, false>> "
     << scope.tangent.name << "_ad(" << scope.tangent.name << "_D6);\n";
  os << "\n    " << model.name() << "_compute(\n";
  bool first = true;
  for (auto const &a : canonical_arguments(RecipeView{model})) {
    if (!first) os << ",\n";
    first = false;
    switch (a.role) {
    case ArgSpec::Role::ScalarParam:
      os << "        " << a.name;
      break;
    case ArgSpec::Role::TensorInput:
    case ArgSpec::Role::TensorOutput:
    case ArgSpec::Role::TensorTangentOutput:
      os << "        " << a.name << "_ad";
      break;
    case ArgSpec::Role::ScalarInput:
    case ArgSpec::Role::StateOld:
    case ArgSpec::Role::StateCurrentRead:
    case ArgSpec::Role::TimeStep:
    case ArgSpec::Role::ScalarOutput:
    case ArgSpec::Role::NewtonStateOut:
      throw std::runtime_error(
          "CalculiXExternalTarget: internal error — unrejected role reached the "
          "call site for '" + a.name + "'");
    }
  }
  os << ");\n";
  detail::emit_stiff21_packing(os, scope.tangent.name + "_D6", "tangent_stiff",
                               "icmd", "    ");
  os << "  }\n";
  os << "};\n\n";

  os << "ncg_material const &thread_state() {\n";
  os << "  thread_local ncg_material const evaluator;\n";
  os << "  return evaluator;\n";
  os << "}\n\n";
  os << "} // namespace\n\n";

  // The exported entry point. STATEV0/STATEV1 are [[maybe_unused]] but stay
  // NAMED for the future history round-trip.
  os << kExternalSignature << " {\n";
  os << "  thread_state().evaluate(MPROPS, STRAN1, STRESS, DDSDDE, *icmd);\n";
  os << "}\n";

  return {EmittedFile{model.name() + "_ext.cpp", os.str(), "",
                      EmittedFile::Kind::Source}};
}

auto CalculiXExternalTarget::target_name() const -> std::string {
  return "CalculiXExternal";
}

} // namespace numsim::codegen
