#include <numsim_codegen/targets/calculix_external.h>

#include "calculix_boundary.h"

#include <numsim_codegen/recipe.h>

#include <cctype>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace numsim::codegen {

namespace {

// CalculiX external-behaviour ABI (the `calculixptr` typedef in
// call_external_umat_user.c). Under the STANDARD interface the quantities are
// NATIVE: STRAN1=emec (tensorial, abq_std order {11,22,33,12,13,23}),
// STRESS=stre, DDSDDE=stiff(21) packed column-major upper, STATEV0/1=history
// old/new, MPROPS=the *USER MATERIAL constants (NPROPS is ccx's `kode`, not the
// count). The trailing `int size` is the amat length, passed BY VALUE. We name
// only the arguments we use.
constexpr char const *kExternalSignature = R"(extern "C" void NCG_UMAT(
    char const *   /*amat*/,   int const *    /*iel*/,    int const *    /*iint*/,
    int const *    /*NPROPS*/, double const * MPROPS,     double const * STRAN1,
    double const * /*STRAN0*/, double const * /*beta*/,   double const * /*F0*/,
    double const * /*voj*/,    double const * /*F1*/,     double const * /*vj*/,
    int const *    /*ithermal*/, double const * /*TEMP1*/, double const * /*DTIME*/,
    double const * /*time*/,   double const * /*ttime*/,  int const *    icmd,
    int const *    /*ielas*/,  int const *    /*mi*/,     int const *    /*NSTATV*/,
    double const * STATEV0,    double *       STATEV1,    double *       STRESS,
    double *       DDSDDE,      int const *    /*iorien*/, double const * /*pgauss*/,
    double const * /*orab*/,   double *       /*PNEWDT*/, int const *    /*ipkon*/,
    int            /*size*/))";

// Uppercase, alphanumeric-only: the library-name form CalculiX parses out of the
// (uppercased) `@<LIB>_NCG_UMAT` material name. Underscores are dropped so the
// first `_` in the deck name reliably splits LIB from the fixed FUNC `NCG_UMAT`.
// NOTE: this map is lossy (Mat_1, MAT1, mat1 all → MAT1); when generating many
// materials, callers must ensure model names don't collide under it — the .so
// filename is the only namespace (every plugin exports the same NCG_UMAT).
auto library_name(std::string const &model) -> std::string {
  std::string out;
  for (char c : model)
    if (std::isalnum(static_cast<unsigned char>(c)))
      out.push_back(
          static_cast<char>(std::toupper(static_cast<unsigned char>(c))));
  return out;
}

} // namespace

auto CalculiXExternalTarget::emit(ConstitutiveModel const &model) const
    -> std::vector<EmittedFile> {
  std::string const body = model.emit_compute_function(m_la);
  bool const needs_la = body.find(m_la.usage_marker()) != std::string::npos;

  auto const scope =
      detail::scan_calculix_scope(model, "CalculiXExternalTarget");

  auto const lib = library_name(model.name());
  if (lib.empty()) {
    throw std::runtime_error(
        "CalculiXExternalTarget: recipe '" + model.name() +
        "' has no alphanumeric characters in its name, so it maps to an empty "
        "library name (ccx would reject the deck). Rename the model.");
  }

  std::ostringstream os;
  os << "// Auto-generated by numsim-codegen. Do not edit.\n";
  os << "//\n";
  os << "// CalculiX EXTERNAL behaviour (loaded at runtime via dlopen — no ccx\n";
  os << "// recompile). Build it as a shared library:\n";
  os << "//   g++ -std=c++23 -O2 -fPIC -shared this.cpp -I<tmech/include> -o lib"
     << lib << ".so\n";
  os << "// Deck:  *MATERIAL, NAME=@" << lib << "_NCG_UMAT\n";
  os << "//        *USER MATERIAL, CONSTANTS=" << scope.params.size() << "\n";
  os << "// (ccx uppercases the name -> dlopen lib" << lib
     << ".so, dlsym NCG_UMAT.) The CONSTANTS count MUST equal the parameter\n";
  os << "// count (" << scope.params.size()
     << "); MPROPS is read positionally with no length check.\n";
  os << "//\n";
  os << "// Lifecycle: (1) a load-time registry is unnecessary for a single-model\n";
  os << "// library and is where the numsim-materials material would be registered\n";
  os << "// for the stateful path; (2) a stateless evaluator is cached per thread;\n";
  os << "// (3) every call reads the constants + strain, evaluates, packs stress +\n";
  os << "// tangent. Constants are read FRESH each call (CalculiX interpolates the\n";
  os << "// *USER MATERIAL constants by temperature, so they can vary per call).\n\n";
  os << "#include <tmech/tmech.h>\n";
  os << "#include <cmath>\n";
  if (needs_la) {
    for (auto const &inc : m_la.includes()) os << "#include " << inc << "\n";
  }
  os << "\n";
  os << body;
  os << "\n";

  // ── (2) a per-thread STATELESS evaluator: no cached constants ──────────────
  os << "namespace {\n\n";
  os << "// Stateless evaluator, cached once per thread (ccx runs the element\n";
  os << "// loop multi-threaded). It holds NO material constants — those are read\n";
  os << "// from MPROPS on every call, since CalculiX may vary them per call\n";
  os << "// (temperature interpolation) and one library may serve several\n";
  os << "// *MATERIAL blocks. For the future stateful path this is where the\n";
  os << "// numsim-materials material (built once per thread) will live, with\n";
  os << "// per-integration-point history flowing through STATEV each call.\n";
  os << "struct ncg_material {\n";
  os << "  void evaluate(double const *mprops, double const *strain_in,\n";
  os << "                double *stress_out, double *tangent_stiff, int icmd) const {\n";
  for (std::size_t k = 0; k < scope.params.size(); ++k) {
    os << "    double const " << scope.params[k] << " = mprops[" << k << "];\n";
  }
  if (scope.params.empty()) os << "    (void)mprops;\n";
  os << "    tmech::adaptor<double const, 3, 2, tmech::abq_std<3, false>> "
     << scope.strain.name << "_ad(strain_in);\n";
  os << "    tmech::adaptor<double, 3, 2, tmech::abq_std<3, false>> "
     << scope.stress.name << "_ad(stress_out);\n";
  os << "    double " << scope.tangent.name << "_D6[36];\n";
  os << "    tmech::adaptor<double, 3, 4, tmech::abq_std<3, false>> "
     << scope.tangent.name << "_ad(" << scope.tangent.name << "_D6);\n";
  os << "\n    " << model.name() << "_compute(\n";
  bool first = true;
  for (auto const &a : canonical_arguments(RecipeView{model})) {
    if (!first) os << ",\n";
    first = false;
    switch (a.role) {
    case ArgSpec::Role::ScalarParam:
      os << "        " << a.name;
      break;
    case ArgSpec::Role::TensorInput:
    case ArgSpec::Role::TensorOutput:
    case ArgSpec::Role::TensorTangentOutput:
      os << "        " << a.name << "_ad";
      break;
    case ArgSpec::Role::ScalarInput:
    case ArgSpec::Role::StateOld:
    case ArgSpec::Role::StateCurrentRead:
    case ArgSpec::Role::TimeStep:
    case ArgSpec::Role::ScalarOutput:
    case ArgSpec::Role::NewtonStateOut:
      throw std::runtime_error(
          "CalculiXExternalTarget: internal error — unrejected role reached the "
          "call site for '" + a.name + "'");
    }
  }
  os << ");\n";
  detail::emit_stiff21_packing(os, scope.tangent.name + "_D6", "tangent_stiff",
                               "icmd", "    ");
  os << "  }\n";
  os << "};\n\n";

  os << "ncg_material const &thread_state() {\n";
  os << "  thread_local ncg_material const evaluator;\n";
  os << "  return evaluator;\n";
  os << "}\n\n";
  os << "} // namespace\n\n";

  // ── (3) the exported CalculiX external entry point ────────────────────────
  os << kExternalSignature << " {\n";
  os << "  (void)STATEV0;\n";
  os << "  (void)STATEV1; // stateless: no history round-trip yet\n";
  os << "  thread_state().evaluate(MPROPS, STRAN1, STRESS, DDSDDE, *icmd);\n";
  os << "}\n";

  return {EmittedFile{model.name() + "_ext.cpp", os.str(), "",
                      EmittedFile::Kind::Source}};
}

auto CalculiXExternalTarget::target_name() const -> std::string {
  return "CalculiXExternal";
}

} // namespace numsim::codegen
