#include <numsim_codegen/targets/moose_material.h>

#include <numsim_codegen/recipe.h>

#include <ostream>
#include <sstream>
#include <stdexcept>
#include <string>

namespace numsim::codegen {

namespace {

// ─── Type-mapping helpers ──────────────────────────────────────

auto tensor_storage_type(std::size_t rank) -> std::string {
  if (rank == 2) return "RankTwoTensor";
  if (rank == 4) return "RankFourTensor";
  throw std::runtime_error(
      "MooseMaterialTarget: tensor rank " + std::to_string(rank) +
      " has no MOOSE storage type. Only rank 2 (RankTwoTensor) and "
      "rank 4 (RankFourTensor) are supported.");
}

auto input_member_type(SymbolDecl const &i) -> std::string {
  if (i.kind == SymbolDecl::Kind::Scalar) {
    return "MaterialProperty<Real>";
  }
  return std::string{"MaterialProperty<"} + tensor_storage_type(i.rank) + ">";
}

auto output_member_type(OutputDecl const &o) -> std::string {
  if (o.kind == OutputDecl::Kind::Scalar) {
    return "MaterialProperty<Real>";
  }
  return std::string{"MaterialProperty<"} + tensor_storage_type(o.rank) + ">";
}

auto input_storage_type(SymbolDecl const &i) -> std::string {
  if (i.kind == SymbolDecl::Kind::Scalar) {
    return "Real";
  }
  return tensor_storage_type(i.rank);
}

auto output_storage_type(OutputDecl const &o) -> std::string {
  if (o.kind == OutputDecl::Kind::Scalar) {
    return "Real";
  }
  return tensor_storage_type(o.rank);
}

// Escape a user-supplied string for safe inclusion in a C++ string
// literal. Handles the five characters that would otherwise produce
// ill-formed C++:
//   `"`  unescaped quote terminates the literal early
//   `\\` unescaped backslash starts an unintended escape sequence
//   `\n` raw newline in a string literal is forbidden by [lex.string]
//   `\r` produces an embedded CR — implementation-defined behavior
//   `\0` embeds a null byte in the string value, which silently
//         truncates downstream C-string APIs
// Tabs and other control bytes pass through unchanged (ugly but legal).
// Cross-ref #14 → CORR-B4 for a future general-identifier validator
// that would reject non-identifier names at recipe-build time.
auto escape_for_cpp_literal(std::string_view s) -> std::string {
  std::string out;
  out.reserve(s.size());
  for (char c : s) {
    switch (c) {
      case '"':  out += "\\\""; break;
      case '\\': out += "\\\\"; break;
      case '\n': out += "\\n";  break;
      case '\r': out += "\\r";  break;
      case '\0': out += "\\0";  break;
      default:   out += c;      break;
    }
  }
  return out;
}

// ─── Header (.h) emission ──────────────────────────────────────

auto emit_header(ConstitutiveModel const &model) -> std::string {
  std::ostringstream os;
  os << "// Auto-generated by numsim-codegen. Do not edit.\n";
  os << "// MOOSE Material class for constitutive model: " << model.name()
     << "\n\n";
  os << "#pragma once\n\n";
  os << "#include \"Material.h\"\n";
  os << "#include \"RankTwoTensor.h\"\n";
  os << "#include \"RankFourTensor.h\"\n\n";

  os << "class " << model.name() << " : public Material\n";
  os << "{\n";
  os << "public:\n";
  os << "  static InputParameters validParams();\n";
  os << "  " << model.name() << "(const InputParameters & parameters);\n\n";
  os << "protected:\n";
  os << "  virtual void computeQpProperties() override;\n";
  if (!model.state_variables().empty()) {
    os << "  virtual void initQpStatefulProperties() override;\n";
  }
  os << "\n";

  // Parameter members (dt → MOOSE's framework `_dt`, no member — issue #77).
  for (auto const &p : model.parameters()) {
    if (p.name == state_time_step_name) continue;
    os << "  Real const _" << p.name << ";\n";
  }
  os << "\n";

  // Input members — MaterialProperty<...> const refs
  for (auto const &i : model.inputs()) {
    os << "  " << input_member_type(i) << " const & _" << i.name << ";\n";
  }
  os << "\n";

  // State-variable members (issue #77): current is a writable declared
  // property; `_old` is the const previous-step property. Scalar only.
  for (auto const &sv : model.state_variables()) {
    os << "  MaterialProperty<Real> & _" << sv.name << ";\n";
    os << "  const MaterialProperty<Real> & _" << sv.name << "_old;\n";
  }
  if (!model.state_variables().empty()) {
    os << "\n";
  }

  // Output members — declared MaterialProperty<...> refs
  for (auto const &o : model.outputs()) {
    os << "  " << output_member_type(o) << " & _" << o.name << ";\n";
  }

  os << "};\n";
  return os.str();
}

// ─── computeQpProperties body ──────────────────────────────────
//
// The Layer-2 compute function is a template over tensor argument types,
// so we can pass `tmech::adaptor<...full<D>>` directly without copying
// through an intermediate `tmech::tensor`. The adaptor wraps MOOSE's
// contiguous `Real[N*N]` storage; tmech's expression templates write
// results back through the adaptor element-wise, so the only data motion
// is the unavoidable read-from-strain / write-to-stress at the boundary.
void emit_compute_qp_body(std::ostream &os, ConstitutiveModel const &model) {
  // Boundary in: read adaptors over each input tensor's data pointer.
  for (auto const &i : model.inputs()) {
    if (i.kind == SymbolDecl::Kind::Tensor) {
      os << "  tmech::adaptor<double const, " << i.dim << ", " << i.rank
         << ", tmech::full<" << i.dim << ">> " << i.name << "_ad(_" << i.name
         << "[_qp].dataPointer());\n";
    }
  }

  // Boundary out: write adaptors over each output tensor's data pointer.
  // The compute function writes directly through these — no intermediate
  // tmech::tensor needed.
  for (auto const &o : model.outputs()) {
    if (o.kind == OutputDecl::Kind::Tensor) {
      os << "  tmech::adaptor<double, " << o.dim << ", " << o.rank
         << ", tmech::full<" << o.dim << ">> " << o.name << "_ad(_" << o.name
         << "[_qp].dataPointer());\n";
    }
  }

  // Call the Layer 2 compute function. Arguments are built by iterating
  // the SAME canonical order the generated signature uses (issue #77), so
  // the call-site and the function definition cannot drift — each ArgSpec
  // role maps to the MOOSE-side actual argument.
  os << "\n  " << model.name() << "_compute(\n";
  bool first = true;
  for (auto const &a : canonical_arguments(RecipeView{model})) {
    if (!first) os << ",\n";
    first = false;
    switch (a.role) {
    case ArgSpec::Role::ScalarParam:
      os << "      _" << a.name; // getParam-backed Real member
      break;
    case ArgSpec::Role::TimeStep:
      os << "      _dt"; // MOOSE framework timestep
      break;
    case ArgSpec::Role::TensorInput:
    case ArgSpec::Role::TensorOutput:
      os << "      " << a.name << "_ad"; // boundary adaptor
      break;
    default: // ScalarInput / StateOld / StateCurrentRead / ScalarOutput /
             // NewtonStateOut — all MaterialProperty<Real> at this qp
      os << "      _" << a.name << "[_qp]";
      break;
    }
  }
  os << ");\n";
}

// Seed each state variable's declared property to its initial value
// (issue #77). The initial value is a scalar expression — emit it through
// the scalar pipeline so a non-constant initial (referencing parameters,
// say) works too. Scalar state variables only in this slice.
void emit_init_stateful_body(std::ostream &os, ConstitutiveModel const &model) {
  CodeGenContext ctx;
  CodeEmitPipeline pipeline(ctx);
  for (auto const &[name, expr] : model.scalar_symbol_map()) {
    ctx.register_symbol_scalar(expr, name);
  }
  for (auto const &sv : model.state_variables()) {
    auto const &init =
        std::get<cas::expression_holder<cas::scalar_expression>>(
            sv.initial_value);
    ctx.reset();
    auto const rhs = pipeline.scalar().apply(init);
    os << ctx.render_statements();
    os << "  _" << sv.name << "[_qp] = " << rhs << ";\n";
  }
}

// ─── Source (.C) emission ──────────────────────────────────────

auto emit_source(ConstitutiveModel const &model, std::string const &app_name)
    -> std::string {
  std::ostringstream os;
  os << "// Auto-generated by numsim-codegen. Do not edit.\n\n";
  os << "#include \"" << model.name() << ".h\"\n";
  os << "#include <tmech/tmech.h>\n";
  os << "#include <cmath>\n\n";

  // Embed the Layer 2 compute function as an anonymous-namespace inline
  // function at file scope. Keeps the implementation self-contained in
  // a single .C file without leaking the helper into other TUs.
  os << "namespace {\n";
  os << model.emit_compute_function();
  os << "} // namespace\n\n";

  // ── registerMooseObject
  os << "registerMooseObject(\"" << app_name << "\", " << model.name()
     << ");\n\n";

  // ── validParams
  os << "InputParameters\n" << model.name() << "::validParams()\n{\n";
  os << "  InputParameters params = Material::validParams();\n";
  os << "  params.addClassDescription(\"Auto-generated constitutive model "
     << model.name() << "\");\n";
  for (auto const &p : model.parameters()) {
    // `dt` maps to MOOSE's framework timestep `_dt`, not an input-file
    // parameter (issue #77).
    if (p.name == state_time_step_name) continue;
    os << "  params.addParam<Real>(\"" << p.name << "\", " << *p.default_value
       << ", \"" << p.doc << "\");\n";
  }
  for (auto const &i : model.inputs()) {
    os << "  params.addRequiredParam<MaterialPropertyName>(\"" << i.name
       << "\", \"Coupled " << escape_for_cpp_literal(i.role.name)
       << "\");\n";
  }
  os << "  return params;\n";
  os << "}\n\n";

  // ── Constructor: initializer list
  os << model.name() << "::" << model.name()
     << "(const InputParameters & parameters)\n";
  os << "  : Material(parameters)";
  for (auto const &p : model.parameters()) {
    if (p.name == state_time_step_name) continue; // → _dt
    os << ",\n    _" << p.name << "(getParam<Real>(\"" << p.name << "\"))";
  }
  for (auto const &i : model.inputs()) {
    os << ",\n    _" << i.name << "(getMaterialProperty<"
       << input_storage_type(i) << ">(\"" << i.name << "\"))";
  }
  // State variables (issue #77, Phase 2.6): the current value is a declared
  // (stateful) property; the `_old` member reads its previous-step value
  // via getMaterialPropertyOld of the SAME property name (MOOSE versions it
  // automatically). Scalar only in this slice.
  for (auto const &sv : model.state_variables()) {
    os << ",\n    _" << sv.name << "(declareProperty<Real>(\"" << model.name()
       << "_" << sv.name << "\"))";
    os << ",\n    _" << sv.name << "_old(getMaterialPropertyOld<Real>(\""
       << model.name() << "_" << sv.name << "\"))";
  }
  for (auto const &o : model.outputs()) {
    os << ",\n    _" << o.name << "(declareProperty<"
       << output_storage_type(o) << ">(\"" << model.name() << "_" << o.name
       << "\"))";
  }
  os << "\n{\n}\n\n";

  // ── initQpStatefulProperties: seed each state variable to its initial
  // value (MOOSE requires stateful properties to be initialised here).
  if (!model.state_variables().empty()) {
    os << "void\n" << model.name() << "::initQpStatefulProperties()\n{\n";
    emit_init_stateful_body(os, model);
    os << "}\n\n";
  }

  // ── computeQpProperties
  os << "void\n" << model.name() << "::computeQpProperties()\n{\n";
  emit_compute_qp_body(os, model);
  os << "}\n";

  return os.str();
}

} // anonymous namespace

// ─── Public methods ────────────────────────────────────────────

auto MooseMaterialTarget::emit(ConstitutiveModel const &model) const
    -> std::vector<EmittedFile> {
  // Stateful symbols would need old/new MaterialProperty pair handling
  // that the MOOSE backend doesn't implement yet. Fail loudly rather
  // than silently emit a regular read.
  //
  // NOTE: stateful *outputs* (is_stateful == true on an OutputDecl) are
  // NOT guarded here. They are currently accepted silently and produce
  // a regular non-stateful MaterialProperty write, which is semantically
  // wrong for state-variable updates. Tracked in issue #15. When adding
  // the output guard, mirror the pattern below.
  for (auto const &i : model.inputs()) {
    if (i.role.is_stateful) {
      throw std::runtime_error(
          "MooseMaterialTarget: stateful role '" + i.role.name +
          "' on input '" + i.name +
          "' requires the History machinery (old/new MaterialProperty pair, "
          "stateful initialisation) which is not implemented in this phase. "
          "See the numsim-codegen Phase B roadmap.");
    }
  }
  return {
      EmittedFile{model.name() + ".h", emit_header(model),
                  "include/materials", EmittedFile::Kind::Header},
      EmittedFile{model.name() + ".C", emit_source(model, m_app_name),
                  "src/materials", EmittedFile::Kind::Source},
  };
}

auto MooseMaterialTarget::target_name() const -> std::string {
  return "MooseMaterial";
}

} // namespace numsim::codegen
