#include <numsim_codegen/targets/moose_material.h>

#include <numsim_codegen/code_emit/spectral_decompose_emit.h>
#include <numsim_codegen/recipe.h>

#include <cmath>
#include <format>
#include <ostream>
#include <sstream>
#include <stdexcept>
#include <string>

namespace numsim::codegen {

namespace {

// ─── Type-mapping helpers ──────────────────────────────────────

auto tensor_storage_type(std::size_t rank) -> std::string {
  if (rank == 2)
    return "RankTwoTensor";
  if (rank == 4)
    return "RankFourTensor";
  throw std::runtime_error(
      "MooseMaterialTarget: tensor rank " + std::to_string(rank) +
      " has no MOOSE storage type. Only rank 2 (RankTwoTensor) and "
      "rank 4 (RankFourTensor) are supported.");
}

auto input_member_type(SymbolDecl const &i) -> std::string {
  if (i.kind == SymbolDecl::Kind::Scalar) {
    return "MaterialProperty<Real>";
  }
  return std::string{"MaterialProperty<"} + tensor_storage_type(i.rank) + ">";
}

auto output_member_type(OutputDecl const &o) -> std::string {
  if (o.kind == OutputDecl::Kind::Scalar) {
    return "MaterialProperty<Real>";
  }
  return std::string{"MaterialProperty<"} + tensor_storage_type(o.rank) + ">";
}

auto input_storage_type(SymbolDecl const &i) -> std::string {
  if (i.kind == SymbolDecl::Kind::Scalar) {
    return "Real";
  }
  return tensor_storage_type(i.rank);
}

auto output_storage_type(OutputDecl const &o) -> std::string {
  if (o.kind == OutputDecl::Kind::Scalar) {
    return "Real";
  }
  return tensor_storage_type(o.rank);
}

// Phase 5 (issue #37): a consistent tangent (requested via
// add_algorithmic_tangent) is wired to MOOSE's conventional `Jacobian_mult`
// property — the exact name the tensor-mechanics StressDivergence kernels look
// up for the algorithmic tangent. It is FIRST-CLASS in this backend (driven by
// `model.tangents()`), not an ordinary `<Model>_<name>` output a solver would
// never find. The tangent is rank-4; its dim is that of the differentiated
// (stress) output. The single-tangent guard in `emit` keeps `_Jacobian_mult`
// unambiguous (MOOSE has one consistent-tangent slot).
//
// SCOPE (PR #82 review): the bare `"Jacobian_mult"` name is correct for the
// default single-material / no-`base_name` case — the common one — which is
// what the StressDivergence kernels resolve by default. A
// `base_name`-namespaced setup (multiple stacked materials per block) expects
// `<base_name>_Jacobian_mult`; threading a `base_name` parameter through is out
// of scope until a multi-material consumer needs it.
auto tangent_dim(ConstitutiveModel const &model,
                 TangentSpec const &t) -> std::size_t {
  for (auto const &o : model.outputs()) {
    if (o.name == t.of_output && o.kind == OutputDecl::Kind::Tensor) {
      return o.dim;
    }
  }
  // of_output existence/rank are validated by AlgorithmicTangentPass at emit;
  // reaching here means the recipe wasn't built through the supported API.
  throw std::runtime_error(
      "MooseMaterialTarget: consistent tangent '" + t.name +
      "' references tensor output '" + t.of_output +
      "' which is not a declared tensor output of model '" + model.name() +
      "'.");
}

// Escape a user-supplied string for safe inclusion in a C++ string
// literal. Handles the five characters that would otherwise produce
// ill-formed C++:
//   `"`  unescaped quote terminates the literal early
//   `\\` unescaped backslash starts an unintended escape sequence
//   `\n` raw newline in a string literal is forbidden by [lex.string]
//   `\r` produces an embedded CR — implementation-defined behavior
//   `\0` embeds a null byte in the string value, which silently
//         truncates downstream C-string APIs
// Tabs and other control bytes pass through unchanged (ugly but legal).
// Cross-ref #14 → CORR-B4 for a future general-identifier validator
// that would reject non-identifier names at recipe-build time.
auto escape_for_cpp_literal(std::string_view s) -> std::string {
  std::string out;
  out.reserve(s.size());
  for (char c : s) {
    switch (c) {
    case '"':
      out += "\\\"";
      break;
    case '\\':
      out += "\\\\";
      break;
    case '\n':
      out += "\\n";
      break;
    case '\r':
      out += "\\r";
      break;
    case '\0':
      out += "\\0";
      break;
    default:
      out += c;
      break;
    }
  }
  return out;
}

// ─── Header (.h) emission ──────────────────────────────────────

auto emit_header(ConstitutiveModel const &model) -> std::string {
  std::ostringstream os;
  os << "// Auto-generated by numsim-codegen. Do not edit.\n";
  os << "// MOOSE Material class for constitutive model: " << model.name()
     << "\n\n";
  os << "#pragma once\n\n";
  os << "#include \"Material.h\"\n";
  os << "#include \"RankTwoTensor.h\"\n";
  os << "#include \"RankFourTensor.h\"\n\n";

  os << "class " << model.name() << " : public Material\n";
  os << "{\n";
  os << "public:\n";
  os << "  static InputParameters validParams();\n";
  os << "  " << model.name() << "(const InputParameters & parameters);\n\n";
  os << "protected:\n";
  os << "  virtual void computeQpProperties() override;\n";
  if (!model.state_variables().empty()) {
    os << "  virtual void initQpStatefulProperties() override;\n";
  }
  os << "\n";

  // Parameter members (dt → MOOSE's framework `_dt`, no member — issue #77).
  for (auto const &p : model.parameters()) {
    if (p.is_time_step)
      continue;
    os << "  Real const _" << p.name << ";\n";
  }
  os << "\n";

  // Input members — MaterialProperty<...> const refs
  for (auto const &i : model.inputs()) {
    os << "  " << input_member_type(i) << " const & _" << i.name << ";\n";
  }
  os << "\n";

  // State-variable members (issue #77): current is a writable declared
  // property; `_old` is the const previous-step property. Scalar only.
  for (auto const &sv : model.state_variables()) {
    os << "  MaterialProperty<Real> & _" << sv.name << ";\n";
    os << "  const MaterialProperty<Real> & _" << sv.name << "_old;\n";
  }
  if (!model.state_variables().empty()) {
    os << "\n";
  }

  // Output members — declared MaterialProperty<...> refs.
  for (auto const &o : model.outputs()) {
    os << "  " << output_member_type(o) << " & _" << o.name << ";\n";
  }
  // Consistent-tangent member → MOOSE's framework `_Jacobian_mult` (Phase 5).
  for (auto const &t : model.tangents()) {
    (void)t;
    os << "  MaterialProperty<RankFourTensor> & _Jacobian_mult;\n";
  }

  os << "};\n";
  return os.str();
}

// ─── computeQpProperties body ──────────────────────────────────
//
// The Layer-2 compute function is a template over tensor argument types,
// so we can pass `tmech::adaptor<...full<D>>` directly without copying
// through an intermediate `tmech::tensor`. The adaptor wraps MOOSE's
// contiguous `Real[N*N]` storage; tmech's expression templates write
// results back through the adaptor element-wise, so the only data motion
// is the unavoidable read-from-strain / write-to-stress at the boundary.
void emit_compute_qp_body(std::ostream &os, ConstitutiveModel const &model) {
  // Boundary in: read adaptors over each input tensor's data pointer.
  for (auto const &i : model.inputs()) {
    if (i.kind == SymbolDecl::Kind::Tensor) {
      os << "  tmech::adaptor<double const, " << i.dim << ", " << i.rank
         << ", tmech::full<" << i.dim << ">> " << i.name << "_ad(_" << i.name
         << "[_qp].dataPointer());\n";
    }
  }

  // Boundary out: write adaptors over each output tensor's data pointer.
  // The compute function writes directly through these — no intermediate
  // tmech::tensor needed.
  for (auto const &o : model.outputs()) {
    if (o.kind == OutputDecl::Kind::Tensor) {
      os << "  tmech::adaptor<double, " << o.dim << ", " << o.rank
         << ", tmech::full<" << o.dim << ">> " << o.name << "_ad(_" << o.name
         << "[_qp].dataPointer());\n";
    }
  }
  // Consistent-tangent write adaptor over `_Jacobian_mult[_qp]` (Phase 5).
  for (auto const &t : model.tangents()) {
    auto const d = tangent_dim(model, t);
    os << "  tmech::adaptor<double, " << d << ", 4, tmech::full<" << d
       << ">> Jacobian_mult_ad(_Jacobian_mult[_qp].dataPointer());\n";
  }

  // Call the Layer 2 compute function. Arguments are built by iterating
  // the SAME canonical order the generated signature uses (issue #77), so
  // the call-site and the function definition cannot drift — each ArgSpec
  // role maps to the MOOSE-side actual argument.
  os << "\n  " << model.name() << "_compute(\n";
  bool first = true;
  for (auto const &a : canonical_arguments(RecipeView{model})) {
    if (!first)
      os << ",\n";
    first = false;
    // Every role enumerated (PR #78 review #5): no `default:`, so a new
    // ArgSpec::Role is a -Wswitch warning here — keeping read vs write
    // roles from silently merging.
    switch (a.role) {
    case ArgSpec::Role::ScalarParam:
      os << "      _" << a.name; // getParam-backed Real member
      break;
    case ArgSpec::Role::TimeStep:
      os << "      _dt"; // MOOSE framework timestep
      break;
    case ArgSpec::Role::TensorInput:
    case ArgSpec::Role::TensorOutput:
      os << "      " << a.name << "_ad"; // boundary adaptor
      break;
    case ArgSpec::Role::TensorTangentOutput:
      os << "      Jacobian_mult_ad"; // Phase 5: → _Jacobian_mult[_qp]
      break;
    case ArgSpec::Role::ScalarInput:
    case ArgSpec::Role::StateOld:
    case ArgSpec::Role::StateCurrentRead:
    case ArgSpec::Role::ScalarOutput:
    case ArgSpec::Role::NewtonStateOut:
      os << "      _" << a.name << "[_qp]"; // MaterialProperty<Real> at _qp
      break;
    }
  }
  os << ");\n";
}

// Seed each state variable's declared property to its initial value
// (issue #77).
//
// The initial value is inlined into `initQpStatefulProperties` with the
// recipe's BARE symbol names — but MOOSE members are `_`-prefixed, so an
// initial that references a parameter/input would emit an undefined name
// (e.g. `_c[_qp] = 0.5 * K;` where the member is `_K`). Phase 2.6 therefore
// supports CONSTANT initial values only and rejects anything referencing a
// symbol — a loud failure rather than broken generated code (PR #78 review
// #3). Scalar state variables only (#1). A non-constant-initial path
// (routing through a generated `_init` function with `_`-prefixed args, the
// same boundary `_compute` uses) is a tracked follow-up.
void emit_init_stateful_body(std::ostream &os, ConstitutiveModel const &model) {
  for (auto const &sv : model.state_variables()) {
    if (sv.kind != SymbolDecl::Kind::Scalar) {
      throw std::runtime_error(
          "MooseMaterialTarget: tensor state variable '" + sv.name +
          "' is not supported yet (scalar state variables only).");
    }
    auto const &init = std::get<cas::expression_holder<cas::scalar_expression>>(
        sv.initial_value);

    LeafCollector lc;
    lc.collect_scalar(init);
    if (!lc.scalar_names().empty() || !lc.tensor_names().empty()) {
      throw std::runtime_error(
          "MooseMaterialTarget: state variable '" + sv.name +
          "' has a non-constant initial value (it references a symbol). "
          "MOOSE initialisation supports constant initial values only in "
          "this release.");
    }

    CodeGenContext ctx;
    CodeEmitPipeline pipeline(ctx);
    auto const rhs = pipeline.scalar().apply(init);
    os << ctx.render_statements();
    os << "  _" << sv.name << "[_qp] = " << rhs << ";\n";
  }
}

// ─── Source (.C) emission ──────────────────────────────────────

auto emit_source(ConstitutiveModel const &model, std::string const &app_name,
                 LinearAlgebraEmitter const &la) -> std::string {
  // Emit the Layer-2 function first so the linalg-include decision tracks the
  // ACTUAL emitted code (PR #83 round-2 #4): gating on a re-derived coupling
  // predicate could diverge from what was emitted (e.g. a future pass-
  // synthesized coupling) → a missing header for code that uses it. Keying on
  // the emitter's usage marker cannot drift. The SAME `la` drives emission and
  // the include (per-target, injected) so they cannot disagree.
  std::string const body = model.emit_compute_function(la);
  bool const needs_la = body.find(la.usage_marker()) != std::string::npos;
  // Spectral materials pull in the shipped tmech-only runtime helper. Keyed on
  // actual emitted usage via the shared `spectral_runtime_qualifier` constant
  // so it can't drift from what the emitters produced — same principle as the
  // linalg marker.
  bool const needs_spectral =
      body.find(spectral_runtime_qualifier) != std::string::npos;

  std::ostringstream os;
  os << "// Auto-generated by numsim-codegen. Do not edit.\n\n";
  os << "#include \"" << model.name() << ".h\"\n";
  os << "#include <tmech/tmech.h>\n";
  os << "#include <cmath>\n";
  if (needs_spectral) {
    os << "#include <numsim_codegen/runtime/spectral.h>\n";
  }
  // Phase 3b-2b: a coupled local-Newton system's dense solve needs the linalg
  // backend's header(s). MOOSE builds third-party headers under -Werror, so
  // wrap them in libMesh's warning-suppression idiom (a bare include would risk
  // build-breaking warnings inside e.g. Eigen). Requires libMesh built with the
  // backend library available (Eigen is the libMesh default).
  if (needs_la) {
    os << "#include \"libmesh/ignore_warnings.h\"\n";
    for (auto const &inc : la.includes()) {
      os << "#include " << inc << "\n";
    }
    os << "#include \"libmesh/restore_warnings.h\"\n";
  }
  os << "\n";

  // Embed the Layer 2 compute function as an anonymous-namespace inline
  // function at file scope. Keeps the implementation self-contained in
  // a single .C file without leaking the helper into other TUs.
  os << "namespace {\n";
  os << body;
  os << "} // namespace\n\n";

  // ── registerMooseObject
  os << "registerMooseObject(\"" << app_name << "\", " << model.name()
     << ");\n\n";

  // ── validParams
  os << "InputParameters\n" << model.name() << "::validParams()\n{\n";
  os << "  InputParameters params = Material::validParams();\n";
  os << "  params.addClassDescription(\"Auto-generated constitutive model "
     << model.name() << "\");\n";
  for (auto const &p : model.parameters()) {
    // `dt` maps to MOOSE's framework timestep `_dt`, not an input-file
    // parameter (issue #77).
    if (p.is_time_step)
      continue;
    // Security (PR #78 round-5): a non-finite default streams as `nan`/`inf`
    // — not a valid C++ literal — so the generated source wouldn't compile.
    // Fail loudly at emit. (`std::format` also gives shortest round-trip
    // precision vs. ostream's default.)
    if (!std::isfinite(*p.default_value)) {
      throw std::runtime_error(
          "MooseMaterialTarget: parameter '" + p.name +
          "' has a non-finite default value (NaN/inf), which is not a valid "
          "C++ literal. Provide a finite default.");
    }
    // `p.doc` is escaped (it flows into a string literal); a raw `"` would
    // terminate the literal early.
    os << "  params.addParam<Real>(\"" << p.name << "\", "
       << std::format("{}", *p.default_value) << ", \""
       << escape_for_cpp_literal(p.doc) << "\");\n";
  }
  for (auto const &i : model.inputs()) {
    os << "  params.addRequiredParam<MaterialPropertyName>(\"" << i.name
       << "\", \"Coupled " << escape_for_cpp_literal(i.role.name) << "\");\n";
  }
  os << "  return params;\n";
  os << "}\n\n";

  // ── Constructor: initializer list
  os << model.name() << "::" << model.name()
     << "(const InputParameters & parameters)\n";
  os << "  : Material(parameters)";
  for (auto const &p : model.parameters()) {
    if (p.is_time_step)
      continue; // → _dt
    os << ",\n    _" << p.name << "(getParam<Real>(\"" << p.name << "\"))";
  }
  for (auto const &i : model.inputs()) {
    os << ",\n    _" << i.name << "(getMaterialProperty<"
       << input_storage_type(i) << ">(\"" << i.name << "\"))";
  }
  // State variables (issue #77, Phase 2.6): the current value is a declared
  // (stateful) property; the `_old` member reads its previous-step value
  // via getMaterialPropertyOld of the SAME property name (MOOSE versions it
  // automatically). Scalar only in this slice.
  for (auto const &sv : model.state_variables()) {
    os << ",\n    _" << sv.name << "(declareProperty<Real>(\"" << model.name()
       << "_" << sv.name << "\"))";
    os << ",\n    _" << sv.name << "_old(getMaterialPropertyOld<Real>(\""
       << model.name() << "_" << sv.name << "\"))";
  }
  for (auto const &o : model.outputs()) {
    os << ",\n    _" << o.name << "(declareProperty<" << output_storage_type(o)
       << ">(\"" << model.name() << "_" << o.name << "\"))";
  }
  // Consistent tangent → declare the conventional `Jacobian_mult` property so
  // MOOSE's StressDivergence kernels resolve it (Phase 5). Bare name (no model
  // prefix) — that is the name the kernels look up.
  for (auto const &t : model.tangents()) {
    (void)t;
    os << ",\n    _Jacobian_mult(declareProperty<RankFourTensor>(\"Jacobian_"
          "mult\"))";
  }
  os << "\n{\n}\n\n";

  // ── initQpStatefulProperties: seed each state variable to its initial
  // value (MOOSE requires stateful properties to be initialised here).
  if (!model.state_variables().empty()) {
    os << "void\n" << model.name() << "::initQpStatefulProperties()\n{\n";
    emit_init_stateful_body(os, model);
    os << "}\n\n";
  }

  // ── computeQpProperties
  os << "void\n" << model.name() << "::computeQpProperties()\n{\n";
  emit_compute_qp_body(os, model);
  os << "}\n";

  return os.str();
}

} // anonymous namespace

// ─── Public methods ────────────────────────────────────────────

auto MooseMaterialTarget::emit(ConstitutiveModel const &model) const
    -> std::vector<EmittedFile> {
  // Stateful symbols would need old/new MaterialProperty pair handling
  // that the MOOSE backend doesn't implement yet. Fail loudly rather
  // than silently emit a regular read.
  //
  // NOTE: stateful *outputs* (is_stateful == true on an OutputDecl) are
  // NOT guarded here. They are currently accepted silently and produce
  // a regular non-stateful MaterialProperty write, which is semantically
  // wrong for state-variable updates. Tracked in issue #15. When adding
  // the output guard, mirror the pattern below.
  for (auto const &i : model.inputs()) {
    if (i.role.is_stateful) {
      throw std::runtime_error(
          "MooseMaterialTarget: stateful role '" + i.role.name +
          "' on input '" + i.name +
          "' requires the History machinery (old/new MaterialProperty pair, "
          "stateful initialisation) which is not implemented in this phase. "
          "See the numsim-codegen Phase B roadmap.");
    }
  }

  // PR #78 round-3: a MOOSE Material solves its local constitutive system
  // INTERNALLY — there is no outer Newton loop at the material level. An
  // evolution recipe that doesn't `enable_local_newton()` would emit
  // `<sv>_residual`/`<sv>_jacobian` as MOOSE properties that nothing
  // solves, with the state property never advancing: valid-but-dead code.
  // Fail loudly (matching the tensor / non-constant-init guards) — the
  // residual/Jacobian-output mode is for external drivers via the
  // standalone target.
  if (!model.evolution_equations().empty() && !model.local_newton_enabled()) {
    throw std::runtime_error(
        "MooseMaterialTarget: recipe '" + model.name() +
        "' has evolution equations but local Newton solving is not enabled. "
        "Call enable_local_newton() so the generated MOOSE Material solves "
        "its state variables internally. (The residual/Jacobian-output mode "
        "is for external drivers — use StandaloneCxxTarget for that.)");
  }
  // Phase 5 (issue #37): all consistent tangents map to the single framework
  // `_Jacobian_mult` property — more than one would emit a duplicate member /
  // property. MOOSE has exactly one consistent-tangent slot. (Tangents live in
  // `tangents()`, not `outputs()`, on the pre-pass model the backend sees.)
  if (model.tangents().size() > 1) {
    throw std::runtime_error(
        "MooseMaterialTarget: recipe '" + model.name() +
        "' requests more than one consistent tangent "
        "(roles::ConsistentTangent)."
        " MOOSE has a single _Jacobian_mult slot, so only one tangent can be "
        "wired. Emit additional tangents via StandaloneCxxTarget.");
  }
  // PR #82 review: when a tangent is wired, the backend emits a hardcoded
  // `_Jacobian_mult` member. A regular output literally named "Jacobian_mult"
  // would collide with that member (ill-formed C++). The recipe symbol
  // namespace can't know the backend's member name, so guard it here.
  if (!model.tangents().empty()) {
    for (auto const &o : model.outputs()) {
      if (o.name == "Jacobian_mult") {
        throw std::runtime_error(
            "MooseMaterialTarget: recipe '" + model.name() +
            "' has both a consistent tangent and an output named "
            "'Jacobian_mult', which collides with the framework consistent-"
            "tangent member. Rename the output.");
      }
    }
  }
  return {
      EmittedFile{model.name() + ".h", emit_header(model), "include/materials",
                  EmittedFile::Kind::Header},
      EmittedFile{model.name() + ".C", emit_source(model, m_app_name, m_la),
                  "src/materials", EmittedFile::Kind::Source},
  };
}

auto MooseMaterialTarget::target_name() const -> std::string {
  return "MooseMaterial";
}

} // namespace numsim::codegen
