#include <numsim_codegen/targets/numsim_material.h>

#include <numsim_codegen/code_emit/code_emit_pipeline.h>
#include <numsim_codegen/code_emit/codegen_context.h>
#include <numsim_codegen/recipe.h>

#include <numsim_cas/core/diff.h>

#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace numsim::codegen {

namespace {

// First-increment scope guard: exactly one scalar state variable + one scalar
// evolution equation, no tensor I/O. Throws with a pointer to the relevant
// follow-up where a richer case applies.
void check_scope(ConstitutiveModel const &model) {
  auto const svs = model.state_variables();
  auto const eqs = model.evolution_equations();
  if (svs.size() != 1 || eqs.size() != 1) {
    throw std::runtime_error(
        "NumSimMaterialTarget: first increment supports exactly one scalar "
        "state variable with one scalar evolution equation (the rk_integrator "
        "rate contract). Coupled / multi-state systems need the "
        "numsim-materials vector solver (numsim-materials#12).");
  }
  if (svs[0].kind != SymbolDecl::Kind::Scalar) {
    throw std::runtime_error(
        "NumSimMaterialTarget: tensor-valued state is not yet supported "
        "(needs Mandel + the vector solver, numsim-materials#11/#12).");
  }
}

} // namespace

auto NumSimMaterialTarget::emit(ConstitutiveModel const &model) const
    -> std::vector<EmittedFile> {
  check_scope(model);

  auto const &sv = model.state_variables()[0];
  auto const &eq = model.evolution_equations()[0];
  auto const &cur_name = model.symbols()[sv.current_symbol_idx].name;

  // Scalar parameters the rate may reference (skip the framework time-step:
  // the integrator owns discretization, so a rate material never sees `dt`).
  std::vector<SymbolDecl> params;
  std::set<std::string> param_names;
  for (auto const &p : model.parameters()) {
    if (p.is_time_step || p.kind != SymbolDecl::Kind::Scalar) continue;
    params.push_back(p);
    param_names.insert(p.name);
  }

  // Resolve the current-state scalar holder (the diff variable), mirroring
  // detail::build_backward_euler_residual's single symbol-map walk.
  cas::expression_holder<cas::scalar_expression> cur_expr;
  for (auto const &[name, h] : model.scalar_symbol_map()) {
    if (name == cur_name) cur_expr = h;
  }
  if (!cur_expr.is_valid()) {
    throw std::runtime_error(
        "NumSimMaterialTarget: cannot resolve the current-state scalar handle "
        "for '" + sv.name + "' — state/symbol vectors out of sync.");
  }

  // Render `rate = f` and `rate_derivative = ∂f/∂x` with one shared CSE block.
  // Emit-name mapping: the state current → a local (bare `cur_name`, bound from
  // m_<state>.get()); parameters → their member `m_<name>`; anything else keeps
  // its bare name (and, if the rate actually used it, would surface as an
  // unbound identifier — the intended scope-guard signal for this increment).
  CodeGenContext ctx;
  CodeEmitPipeline pipeline(ctx);
  for (auto const &[name, expr] : model.scalar_symbol_map()) {
    if (name == cur_name) {
      ctx.register_symbol_scalar(expr, name);
    } else if (param_names.contains(name)) {
      ctx.register_symbol_scalar(expr, "m_" + name);
    } else {
      ctx.register_symbol_scalar(expr, name);
    }
  }
  ctx.reset(); // clear statements, keep registrations + temp counter
  auto const rate_rhs = pipeline.scalar().apply(eq.rate);
  auto const drate_rhs = pipeline.scalar().apply(cas::diff(eq.rate, cur_expr));
  auto const decls = ctx.render_statements("    ");

  auto const &cls = model.name();

  // ── Material header ────────────────────────────────────────────────
  std::ostringstream h;
  h << "// Auto-generated by numsim-codegen (NumSimMaterialTarget). Do not "
       "edit.\n";
  h << "// Rate-function material for recipe \"" << cls << "\": d" << cur_name
    << "/dt = f(" << cur_name << ").\n";
  h << "// Conforms to the numsim-materials rk_integrator contract: exposes\n";
  h << "// `rate` (= f) and `rate_derivative` (= df/d" << cur_name
    << ") as Local-edge\n";
  h << "// properties; reads " << cur_name
    << " from the integrator's `state`.\n";
  h << "#pragma once\n";
  h << "#include \"numsim-materials/core/material_base.h\"\n";
  h << "#include <utility>\n\n";
  h << "namespace numsim::materials::generated {\n\n";
  h << "template <typename Traits>\n";
  h << "class " << cls << " final\n";
  h << "    : public numsim::materials::material_base<" << cls
    << "<Traits>, Traits> {\n";
  h << "public:\n";
  h << "  using base = numsim::materials::material_base<" << cls
    << "<Traits>, Traits>;\n";
  h << "  using value_type = typename base::value_type;\n";
  h << "  using input_parameter_controller =\n"
       "      typename base::input_parameter_controller;\n\n";

  // Constructor
  h << "  template <typename... Args>\n";
  h << "  explicit " << cls << "(Args&&... args)\n";
  h << "      : base(std::forward<Args>(args)...),\n";
  h << "        m_rate(base::template add_output<value_type>(\n";
  h << "            \"rate\", &" << cls << "::compute)),\n";
  h << "        m_rate_derivative(\n";
  h << "            base::template add_output<value_type>(\"rate_derivative\")),"
       "\n";
  for (auto const &p : params) {
    h << "        m_" << p.name
      << "(base::template get_parameter<value_type>(\"" << p.name << "\")),\n";
  }
  h << "        m_integrator_source(\n";
  h << "            base::template "
       "get_parameter<std::string>(\"integrator_source\")),\n";
  h << "        m_" << cur_name << "(base::template add_input<value_type>(\n";
  h << "            m_integrator_source, \"state\",\n";
  h << "            numsim::materials::EdgeKind::Local)) {}\n\n";

  // parameters() schema
  h << "  static input_parameter_controller parameters() {\n";
  h << "    input_parameter_controller para{base::parameters()};\n";
  for (auto const &p : params) {
    if (p.default_value.has_value()) {
      h << "    para.template insert<value_type>(\"" << p.name
        << "\").template add<numsim_core::set_default>(value_type{"
        << *p.default_value << "});\n";
    } else {
      h << "    para.template insert<value_type>(\"" << p.name
        << "\").template add<numsim_core::is_required>();\n";
    }
  }
  h << "    para.template insert<std::string>(\"integrator_source\")\n";
  h << "        .template add<numsim_core::is_required>();\n";
  h << "    return para;\n";
  h << "  }\n\n";

  // compute()
  h << "  // rate = f(" << cur_name << "); rate_derivative = df/d" << cur_name
    << " (cas::diff).\n";
  h << "  void compute() {\n";
  h << "    const auto " << cur_name << " = m_" << cur_name << ".get();\n";
  if (!decls.empty()) h << decls;
  h << "    m_rate = " << rate_rhs << ";\n";
  h << "    m_rate_derivative = " << drate_rhs << ";\n";
  h << "  }\n\n";

  // members
  h << "private:\n";
  h << "  value_type& m_rate;\n";
  h << "  value_type& m_rate_derivative;\n";
  for (auto const &p : params) {
    h << "  const value_type& m_" << p.name << ";\n";
  }
  h << "  const std::string& m_integrator_source;\n";
  h << "  const numsim::materials::input_property<value_type,\n";
  h << "      numsim::materials::property_traits>& m_" << cur_name << ";\n";
  h << "};\n\n";
  h << "} // namespace numsim::materials::generated\n";

  // ── JSON config (wires an integrator + this material) ──────────────
  std::ostringstream j;
  j << "{\n";
  j << "  \"materials\": [\n";
  j << "    { \"name\": \"integrator\", \"type\": \"rk_integrator\",\n";
  j << "      \"function\": \"" << cls << "\",\n";
  j << "      \"step_size\": 0.01, \"tableau\": \"implicit_euler\",\n";
  j << "      \"tolerance\": 1e-12, \"max_iter\": 50 },\n";
  j << "    { \"name\": \"" << cls << "\", \"type\": \"" << cls << "\",\n";
  j << "      \"integrator_source\": \"integrator\"";
  for (auto const &p : params) {
    j << ",\n      \"" << p.name
      << "\": " << (p.default_value.has_value() ? *p.default_value : 0.0);
  }
  j << " }\n";
  j << "  ]\n";
  j << "}\n";

  return {
      EmittedFile{cls + ".h", h.str(), "include/materials",
                  EmittedFile::Kind::Header},
      EmittedFile{cls + ".config.json", j.str(), "", EmittedFile::Kind::Other},
  };
}

auto NumSimMaterialTarget::target_name() const -> std::string {
  return "NumSimMaterial";
}

} // namespace numsim::codegen
