#include <numsim_codegen/targets/standalone_cxx.h>

#include <numsim_codegen/code_emit/spectral_decompose_emit.h>
#include <numsim_codegen/recipe.h>

#include <sstream>

namespace numsim::codegen {

auto StandaloneCxxTarget::emit(ConstitutiveModel const &model) const
    -> std::vector<EmittedFile> {
  // Emit the function first so both include decisions track ACTUAL usage in
  // the emitted code via the shared predicates (uses_linear_algebra /
  // uses_spectral_runtime, #139) — keying on the emitters' markers cannot
  // drift from what was emitted. The library is whatever
  // default_linear_algebra_emitter() selects.
  std::string const body = model.emit_compute_function(m_la);
  bool const needs_la = uses_linear_algebra(body, m_la);
  bool const needs_spectral = uses_spectral_runtime(body);

  std::ostringstream os;
  os << "// Auto-generated by numsim-codegen. Do not edit.\n\n";
  os << "#pragma once\n";
  os << "#include <tmech/tmech.h>\n";
  os << "#include <cmath>\n";
  if (needs_spectral) {
    os << "#include <numsim_codegen/runtime/spectral.h>\n";
  }
  // Phase 3b-2b: a coupled local-Newton system's dense solve needs the linalg
  // backend's header(s) (e.g. <Eigen/Dense>).
  if (needs_la) {
    for (auto const &inc : m_la.includes()) {
      os << "#include " << inc << "\n";
    }
  }
  os << "\n";
  os << body;
  return {EmittedFile{model.name() + ".h", os.str(), "",
                      EmittedFile::Kind::Header}};
}

auto StandaloneCxxTarget::target_name() const -> std::string {
  return "StandaloneCxx";
}

} // namespace numsim::codegen
