#include <numsim_codegen/targets/standalone_cxx.h>

#include <numsim_codegen/recipe.h>

#include <sstream>

namespace numsim::codegen {

auto StandaloneCxxTarget::emit(ConstitutiveModel const &model) const
    -> std::vector<EmittedFile> {
  std::ostringstream os;
  os << "// Auto-generated by numsim-codegen. Do not edit.\n\n";
  os << "#pragma once\n";
  os << "#include <tmech/tmech.h>\n";
  os << "#include <cmath>\n";
  // Phase 3b-2b: a coupled local-Newton system's dense solve uses Eigen.
  if (has_coupled_local_newton(model)) {
    os << "#include <Eigen/Dense>\n";
  }
  os << "\n";
  os << model.emit_compute_function();
  return {EmittedFile{model.name() + ".h", os.str(), "",
                      EmittedFile::Kind::Header}};
}

auto StandaloneCxxTarget::target_name() const -> std::string {
  return "StandaloneCxx";
}

} // namespace numsim::codegen
