#include <numsim_codegen/targets/standalone_cxx.h>

#include <numsim_codegen/code_emit/spectral_decompose_emit.h>
#include <numsim_codegen/recipe.h>

#include <sstream>

namespace numsim::codegen {

auto StandaloneCxxTarget::emit(ConstitutiveModel const &model) const
    -> std::vector<EmittedFile> {
  // Emit the function first so the linalg-include decision tracks ACTUAL usage
  // in the emitted code, not a re-derived coupling predicate (PR #83 round-2
  // #4) — keying on the emitter's usage marker cannot drift from what was
  // emitted. The library is whatever default_linear_algebra_emitter() selects.
  std::string const body = model.emit_compute_function(m_la);
  bool const needs_la = body.find(m_la.usage_marker()) != std::string::npos;
  // Key the spectral-runtime include on ACTUAL emitted usage — the spectral
  // handlers emit calls under `spectral_runtime_qualifier` (spectral_decompose
  // / divided_difference / confluent_derivative). Sharing that constant with
  // the emitters means a namespace rename can't silently drop the include. Same
  // no-drift principle as the linalg marker above.
  bool const needs_spectral =
      body.find(spectral_runtime_qualifier) != std::string::npos;

  std::ostringstream os;
  os << "// Auto-generated by numsim-codegen. Do not edit.\n\n";
  os << "#pragma once\n";
  os << "#include <tmech/tmech.h>\n";
  os << "#include <cmath>\n";
  if (needs_spectral) {
    os << "#include <numsim_codegen/runtime/spectral.h>\n";
  }
  // Phase 3b-2b: a coupled local-Newton system's dense solve needs the linalg
  // backend's header(s) (e.g. <Eigen/Dense>).
  if (needs_la) {
    for (auto const &inc : m_la.includes()) {
      os << "#include " << inc << "\n";
    }
  }
  os << "\n";
  os << body;
  return {EmittedFile{model.name() + ".h", os.str(), "",
                      EmittedFile::Kind::Header}};
}

auto StandaloneCxxTarget::target_name() const -> std::string {
  return "StandaloneCxx";
}

} // namespace numsim::codegen
