#ifndef NUMSIM_CODEGEN_TARGETS_MOOSE_MATERIAL_H
#define NUMSIM_CODEGEN_TARGETS_MOOSE_MATERIAL_H

#include <numsim_codegen/targets/target.h>

#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace numsim::codegen {

// MOOSE Material backend. Generates a header + source pair:
//
//   <ModelName>.h  — Material class declaration with validParams,
//                    constructor signature, MaterialProperty members.
//   <ModelName>.C  — Material class implementation: validParams body,
//                    constructor body, computeQpProperties body that
//                    delegates to the Layer 2 compute function.
//
// The Layer 2 compute function is embedded as an inline header at the
// top of the .C file. The boundary conversion uses tmech::adaptor over
// MOOSE's RankTwoTensor / RankFourTensor raw data pointers — assumes the
// underlying storage is contiguous row-major doubles, which matches
// MOOSE's internal layout for RankTwoTensorTempl<Real> / RankFourTensorTempl.
//
// Inputs tagged with InputRole::Strain become MaterialProperty<RankTwoTensor>
// reads. Outputs tagged with OutputRole::Stress become
// MaterialProperty<RankTwoTensor> writes. Other roles are mapped likewise.
class MooseMaterialTarget : public Target {
public:
  explicit MooseMaterialTarget(std::string app_name = "MyApp")
      : m_app_name(std::move(app_name)) {}

  [[nodiscard]] auto emit(ConstitutiveModel const &model) const
      -> std::vector<EmittedFile> override {
    // History symbols would need old/new MaterialProperty pair handling
    // that the MOOSE backend doesn't implement yet. Fail loudly rather
    // than silently emit a regular read.
    for (auto const &i : model.inputs()) {
      if (i.role == InputRole::History) {
        throw std::runtime_error(
            "MooseMaterialTarget: InputRole::History on input '" + i.name +
            "' requires the History machinery (old/new MaterialProperty pair, "
            "stateful initialisation) which is not implemented in this phase. "
            "See the numsim-codegen Phase B roadmap.");
      }
    }
    return {
        EmittedFile{model.name() + ".h", emit_header(model),
                    "include/materials", EmittedFile::Kind::Header},
        EmittedFile{model.name() + ".C", emit_source(model),
                    "src/materials", EmittedFile::Kind::Source},
    };
  }

  [[nodiscard]] auto target_name() const -> std::string override {
    return "MooseMaterial";
  }

private:
  // ─── Header (.h) emission ──────────────────────────────────────

  [[nodiscard]] auto emit_header(ConstitutiveModel const &model) const
      -> std::string {
    std::ostringstream os;
    os << "// Auto-generated by numsim-codegen. Do not edit.\n";
    os << "// MOOSE Material class for constitutive model: "
       << model.name() << "\n\n";
    os << "#pragma once\n\n";
    os << "#include \"Material.h\"\n";
    os << "#include \"RankTwoTensor.h\"\n";
    os << "#include \"RankFourTensor.h\"\n\n";

    os << "class " << model.name() << " : public Material\n";
    os << "{\n";
    os << "public:\n";
    os << "  static InputParameters validParams();\n";
    os << "  " << model.name() << "(const InputParameters & parameters);\n\n";
    os << "protected:\n";
    os << "  virtual void computeQpProperties() override;\n\n";

    // Parameter members
    for (auto const &p : model.parameters()) {
      os << "  Real const _" << p.name << ";\n";
    }
    os << "\n";

    // Input members — MaterialProperty<...> const refs
    for (auto const &i : model.inputs()) {
      os << "  " << input_member_type(i) << " const & _" << i.name << ";\n";
    }
    os << "\n";

    // Output members — declared MaterialProperty<...> refs
    for (auto const &o : model.outputs()) {
      os << "  " << output_member_type(o) << " & _" << o.name << ";\n";
    }

    os << "};\n";
    return os.str();
  }

  // ─── Source (.C) emission ──────────────────────────────────────

  [[nodiscard]] auto emit_source(ConstitutiveModel const &model) const
      -> std::string {
    std::ostringstream os;
    os << "// Auto-generated by numsim-codegen. Do not edit.\n\n";
    os << "#include \"" << model.name() << ".h\"\n";
    os << "#include <tmech/tmech.h>\n";
    os << "#include <cmath>\n\n";

    // Embed the Layer 2 compute function as an anonymous-namespace inline
    // function at file scope. Keeps the implementation self-contained in
    // a single .C file without leaking the helper into other TUs.
    os << "namespace {\n";
    os << model.emit_compute_function();
    os << "} // namespace\n\n";

    // ── registerMooseObject
    os << "registerMooseObject(\"" << m_app_name << "\", " << model.name()
       << ");\n\n";

    // ── validParams
    os << "InputParameters\n" << model.name() << "::validParams()\n{\n";
    os << "  InputParameters params = Material::validParams();\n";
    os << "  params.addClassDescription(\"Auto-generated constitutive model "
       << model.name() << "\");\n";
    for (auto const &p : model.parameters()) {
      os << "  params.addParam<Real>(\"" << p.name << "\", "
         << *p.default_value << ", \"" << p.doc << "\");\n";
    }
    for (auto const &i : model.inputs()) {
      os << "  params.addRequiredParam<MaterialPropertyName>(\"" << i.name
         << "\", \"Coupled " << input_role_doc(i.role) << "\");\n";
    }
    os << "  return params;\n";
    os << "}\n\n";

    // ── Constructor: initializer list
    os << model.name() << "::" << model.name()
       << "(const InputParameters & parameters)\n";
    os << "  : Material(parameters)";
    for (auto const &p : model.parameters()) {
      os << ",\n    _" << p.name << "(getParam<Real>(\"" << p.name << "\"))";
    }
    for (auto const &i : model.inputs()) {
      os << ",\n    _" << i.name << "(getMaterialProperty<"
         << input_storage_type(i) << ">(\"" << i.name << "\"))";
    }
    for (auto const &o : model.outputs()) {
      os << ",\n    _" << o.name << "(declareProperty<"
         << output_storage_type(o) << ">(\"" << model.name() << "_"
         << o.name << "\"))";
    }
    os << "\n{\n}\n\n";

    // ── computeQpProperties
    os << "void\n" << model.name() << "::computeQpProperties()\n{\n";
    emit_compute_qp_body(os, model);
    os << "}\n";

    return os.str();
  }

  // Emit the body of computeQpProperties.
  //
  // The Layer-2 compute function is a template over tensor argument types,
  // so we can pass `tmech::adaptor<...full<D>>` directly without copying
  // through an intermediate `tmech::tensor`. The adaptor wraps MOOSE's
  // contiguous `Real[N*N]` storage; tmech's expression templates write
  // results back through the adaptor element-wise, so the only data motion
  // is the unavoidable read-from-strain / write-to-stress at the boundary.
  void emit_compute_qp_body(std::ostream &os,
                            ConstitutiveModel const &model) const {
    // Boundary in: read adaptors over each input tensor's data pointer.
    for (auto const &i : model.inputs()) {
      if (i.kind == SymbolDecl::Kind::Tensor) {
        os << "  tmech::adaptor<double const, " << i.dim << ", " << i.rank
           << ", tmech::full<" << i.dim << ">> " << i.name
           << "_ad(_" << i.name << "[_qp].dataPointer());\n";
      }
    }

    // Boundary out: write adaptors over each output tensor's data pointer.
    // The compute function writes directly through these — no intermediate
    // tmech::tensor needed.
    for (auto const &o : model.outputs()) {
      if (o.kind == OutputDecl::Kind::Tensor) {
        os << "  tmech::adaptor<double, " << o.dim << ", " << o.rank
           << ", tmech::full<" << o.dim << ">> " << o.name
           << "_ad(_" << o.name << "[_qp].dataPointer());\n";
      }
    }

    // Call the Layer 2 compute function with adaptors / scalar refs.
    os << "\n  " << model.name() << "_compute(\n";
    bool first = true;
    for (auto const &p : model.parameters()) {
      if (!first) os << ",\n";
      first = false;
      os << "      _" << p.name;
    }
    for (auto const &i : model.inputs()) {
      if (!first) os << ",\n";
      first = false;
      if (i.kind == SymbolDecl::Kind::Tensor) {
        os << "      " << i.name << "_ad";
      } else {
        os << "      _" << i.name << "[_qp]";
      }
    }
    for (auto const &o : model.outputs()) {
      if (!first) os << ",\n";
      first = false;
      if (o.kind == OutputDecl::Kind::Tensor) {
        os << "      " << o.name << "_ad";
      } else {
        os << "      _" << o.name << "[_qp]";
      }
    }
    os << ");\n";
  }

  // ─── Type-mapping helpers ──────────────────────────────────────

  static auto input_member_type(SymbolDecl const &i) -> std::string {
    if (i.kind == SymbolDecl::Kind::Scalar) {
      return "MaterialProperty<Real>";
    }
    return std::string{"MaterialProperty<"} + tensor_storage_type(i.rank) + ">";
  }

  static auto output_member_type(OutputDecl const &o) -> std::string {
    if (o.kind == OutputDecl::Kind::Scalar) {
      return "MaterialProperty<Real>";
    }
    return std::string{"MaterialProperty<"} + tensor_storage_type(o.rank) + ">";
  }

  static auto input_storage_type(SymbolDecl const &i) -> std::string {
    if (i.kind == SymbolDecl::Kind::Scalar) {
      return "Real";
    }
    return tensor_storage_type(i.rank);
  }

  static auto output_storage_type(OutputDecl const &o) -> std::string {
    if (o.kind == OutputDecl::Kind::Scalar) {
      return "Real";
    }
    return tensor_storage_type(o.rank);
  }

  static auto tensor_storage_type(std::size_t rank) -> std::string {
    if (rank == 2) return "RankTwoTensor";
    if (rank == 4) return "RankFourTensor";
    throw std::runtime_error(
        "MooseMaterialTarget: tensor rank " + std::to_string(rank) +
        " has no MOOSE storage type. Only rank 2 (RankTwoTensor) and "
        "rank 4 (RankFourTensor) are supported.");
  }

  static auto input_role_doc(InputRole role) -> std::string {
    switch (role) {
      case InputRole::Strain:             return "strain tensor";
      case InputRole::StrainIncrement:    return "strain increment tensor";
      case InputRole::DeformationGradient:return "deformation gradient";
      case InputRole::Stress:             return "stress tensor";
      case InputRole::Temperature:        return "temperature";
      case InputRole::History:            return "history variable";
      case InputRole::Other:              return "input";
    }
    return "input";
  }

  std::string m_app_name;
};

} // namespace numsim::codegen

#endif // NUMSIM_CODEGEN_TARGETS_MOOSE_MATERIAL_H
