#ifndef NUMSIM_CODEGEN_TARGETS_STANDALONE_CXX_H
#define NUMSIM_CODEGEN_TARGETS_STANDALONE_CXX_H

#include <numsim_codegen/targets/target.h>

#include <sstream>

namespace numsim::codegen {

// Plain C++ target — emits a single inline header containing the generic
// compute function with the user's declared signature. No framework
// boundary; the user calls the function directly with tmech::tensor
// arguments. This is the simplest target and the one used by tests.
class StandaloneCxxTarget : public Target {
public:
  [[nodiscard]] auto emit(ConstitutiveModel const &model) const
      -> std::vector<EmittedFile> override {
    std::ostringstream os;
    os << "// Auto-generated by numsim-codegen. Do not edit.\n\n";
    os << "#pragma once\n";
    os << "#include <tmech/tmech.h>\n";
    os << "#include <cmath>\n\n";
    os << model.emit_compute_function();
    return {EmittedFile{model.name() + ".h", os.str(), "", EmittedFile::Kind::Header}};
  }

  [[nodiscard]] auto target_name() const -> std::string override {
    return "StandaloneCxx";
  }
};

} // namespace numsim::codegen

#endif // NUMSIM_CODEGEN_TARGETS_STANDALONE_CXX_H
